# Generated by Django 5.1.2 on 2024-10-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_customuser_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cpf',
        ),
    ]
