# Generated by Django 5.1.2 on 2024-10-24 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_alter_company_st_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='O CNPJ deve ter 14 dígitos', regex='^\\d{14}$')]),
        ),
    ]
