# Generated by Django 5.1.2 on 2024-10-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_alter_company_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residencial'), ('commercial', 'Comercial')], default='commercial', max_length=15, null=True),
        ),
    ]
