# Generated by Django 5.1.2 on 2024-10-24 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0013_company_date_last_update_company_date_register_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access.company'),
        ),
    ]
