# Generated by Django 5.1.2 on 2024-10-24 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0014_profile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='access.company'),
        ),
    ]
