"""
Django settings for mesa project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# DATE_FORMAT = "d/m/Y"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9b^bn4tnfv!8t6hd_nb#z38gppxge%-n%y81s*+qrvs1fu7asf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# AUTH_USER_MODEL = 'access.CustomUser'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'import_export',
    # 'django.contrib.sites',
    'access',
    'allauth',
    'allauth.account',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'mesa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'mesa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
    # Backend customizado
    'access.authentication_backend.EmailOrUsernameModelBackend',  
]

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#  All Auth Configurations
# LOGIN_REDIRECT_URL = "/base_account.html"
# LOGIN_URL = "account_login"

# SMTP Configure
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "contato@tegge.com.br"
# EMAIL_HOST_PASSWORD = "lwpb jalz baim spmz"
# DEFAULT_FROM_EMAIL = "contato@tegge.com.br"

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


UNFOLD = {
    "SITE_TITLE": "Sistema de crédito Tegge-BRB",
    "SITE_HEADER": "Mesa Tegge-BRB",
    "SITE_URL": "/",
    # "SITE_ICON": {
    #     "light": lambda request: static("images/icons/icon-light.svg"),  # light mode
    #     "dark": lambda request: static("images/icons/icon-dark.svg"),  # dark mode
    # },  
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("images/icons/favicon.svg"),
        },
    ],
    "COLORS": {
        "font": {
            "subtle-light": "107 114 128",
            "subtle-dark": "156 163 175",
            "default-light": "75 85 99",
            "default-dark": "209 213 219",
            "important-light": "17 24 39",
            "important-dark": "243 244 246",
        },
        'primary': {
        '50': '#eff9ff',
        '100': '#daf0ff',
        '200': '#bee6ff',
        '300': '#91d8ff',
        '400': '#5ec0fc',
        '500': '#38a2f9',
        '600': '#2285ee',
        '700': '#1969d1',
        '800': '#1c59b1',
        '900': '#1c4c8c',
        '950': '#163055',
        },
    },
    "LOGIN": {
        "image": lambda request: static("images/backgrounds/login-bg.png"),
    },
    "SIDEBAR": {
        "show_search": False,  # Search in applications and models names
        "show_all_applications": True,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _("Admin"),
                "separator": False,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Company"),
                        "icon": "corporate_fare",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:access_company_changelist"),
                        # "badge": "sample_app.badge_callback",
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Profile"),
                        "icon": "person_add",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:access_profile_changelist"),
                        # "badge": "sample_app.badge_callback",
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("User"),
                        "icon": "person",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        # "badge": "sample_app.badge_callback",
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Group"),
                        "icon": "group",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        # "badge": "sample_app.badge_callback",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Emails"),
                        "icon": "mail",
                        "link": reverse_lazy("admin:account_emailaddress_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    # {
                    #     "title": _("Users"),
                    #     "icon": "people",
                    #     "link": reverse_lazy("admin:users_user_changelist"),
                    # },
                ],
            },
            {
                "title": _("Operação"),
                "separator": False,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Configurações"),
                        "icon": "settings",
                        "link": reverse_lazy("admin:index"),
                        "permission": lambda request: request.user.is_authenticated,
                    },
                ],
            },
        ],
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    # Definição de tempo de expiração para os tokens
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Tempo de vida do token de acesso
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),    # Tempo de vida do token de atualização

    # Algoritmo e chave para assinar o token
    # 'ALGORITHM': 'HS256',  # Algoritmo para assinar o token
    # 'SIGNING_KEY': settings.SECRET_KEY,  # Chave secreta do Django para assinar o token

    # Configurações de autenticação básica
    'AUTH_HEADER_TYPES': ('Bearer',),  # Tipo de autenticação no cabeçalho
    # 'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',  # Nome do cabeçalho

    # Definições básicas do comportamento dos tokens
    'ROTATE_REFRESH_TOKENS': False,  # Não rotacionar tokens de refresh automaticamente
    'BLACKLIST_AFTER_ROTATION': False,  # Não invalidar tokens de refresh após uso
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    
    # Configurações de serializers
    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',  # Serializer para obter tokens
    'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',  # Serializer para renovar tokens
    'TOKEN_VERIFY_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenVerifySerializer',  # Serializer para verificar tokens
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'mesa.tegge API',
    'DESCRIPTION': 'Documentação para produto INSS',
    'VERSION': 'v1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'mesa.tegge API',
    'DESCRIPTION': 'Documentação para produto INSS BRB',
    'VERSION': 'v1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'docExpansion': 'none',
        'defaultModelsExpandDepth': -1,
        'defaultModelRendering': 'model',
        'displayOperationId': True,
        'displayRequestDuration': True,
        'filter': True,
        'showRequestHeaders': True,
        'showExtensions': True,
        'showCommonExtensions': True,
        'supportedSubmitMethods': ['get', 'post', 'put', 'delete', 'patch',],
        # Custom logo
        'customCss': '''
            .swagger-ui .topbar { 
                background: url('/static/images/logo-dark.png') no-repeat;
                background-size: contain;
                height: 50px; /* Ajuste o tamanho do cabeçalho conforme necessário */
            }
        ''',
    },
}